### ISSUE TITLE
Add CSS typographic features?

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#14]
See: http://utility-opentype.kennethormandy.com/.

**Comment by DaveOrDead** [comment]
Seems like this would be overkill to me if we're looking to keep it lightweight.  Maybe something we add if we come across a need for it?

**Comment by chris-pearce** [comment]
Yeah I see the argument in keeping things lightweight, I do feel though some of it is more of a Base setting worthy of being part of a CSS lib like Shell. Need to investigate the CSS more though—man there's a lot more advanced typography things you can do nowadays, just wanna make sure we're not forgetting about them.

**Comment by chris-pearce** [comment]
Closing this for now.
