### ISSUE TITLE
Grid > Negative bottom margin bug

### ISSUE THREAD

**Issue by DaveOrDead** [campaignmonitor/shell#2]
Steps to reproduce:
- create component with 2 col grid inside (no modifiers).
- put placeholder content in the cells
  - Put background colour on wrapping component to help visualise bug
- create another 2 col grid beneath this with a heading in one of the cells.

You will see the second grid has been pulled up under the first so the heading is cut in half.

**Comment by chris-pearce** [comment]
I feel really strongly vertical spacing should be opt in.

**Comment by chris-pearce** [comment]
Fixed in #6.
