### ISSUE TITLE
Export `scss` libraries via object props

### ISSUE THREAD

**Issue by tamoore** [campaignmonitor/shell#23]
It would be great if we could expose all of shell's libraries via an `npm` entry js.

For example:

``` javascript
var shell = require('./src/shell.scss');
var settings = require('./src/_settings.scss');

module.exports = {
  settings: settings,
  shell: shell,
  ...
};
```

This would allow `npm` modules (and webpack) to consume either the whole scss lib or just relevant libraries.

**Comment by chris-pearce** [comment]
Fixed in #30
