### ISSUE TITLE
Reassess the use of Sass `floor` and `ceil` functions in Settings

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#38]
https://gist.github.com/terkel/4373420 might be what we need.

**Comment by DaveOrDead** [comment]
I ran some tests `ceil` and `floor` seem to be working fine i.e rounding to nearest whole number

**Comment by DaveOrDead** [comment]
reviewed with @chris-pearce.  Our current usage is only relevant if there is an override on `$shell-g-base-number` which makes it an _odd_ value.

Decided to keep them in for this case.
