### ISSUE TITLE
Remove base naming convention from Shell's settings

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#52]
We're doing this as **base** isn't used in the typography scale, the base setting is just `$shell-g-font-size`, so instead of `$shell-g-spacing-base` go with `$shell-g-spacing`. Other places **base** word is used: 
- https://github.com/campaignmonitor/shell/blob/master/src/_settings.scss#L101-L105
- https://github.com/campaignmonitor/shell/blob/master/src/_settings.scss#L167-L168
- https://github.com/campaignmonitor/shell/blob/master/src/_settings.scss#L608-L614
- https://github.com/campaignmonitor/shell/blob/master/src/_settings.scss#L726-L732

**Comment by DaveOrDead** [comment]
Sorted :) https://github.com/campaignmonitor/shell/pull/53
