### ISSUE TITLE
New Grid modifiers

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#9]
There's a need to add modifiers at the individual grid item level with the most common treatment being different alignments options using `flex-self`. Also making all grid item children equal height.

**Comment by DaveOrDead** [comment]
PR for equal height columns done.  Can you expand on the `flex-self` and I'll get that done.  I'm not entirely sure what the requirement is

**Comment by chris-pearce** [comment]
> PR for equal height columns done. 

Great :+1:. 

Ah I think I meant `align-self`, I felt that the need to apply this to particular grid items would be needed but I might be wrong?

**Comment by chris-pearce** [comment]
@kllevin might have some input on new grid modifiers.
